import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { join, relative, resolve, sep } from "node:path";
import { pathToFileURL } from "node:url";
import type { ImageContent } from "@earendil-works/pi-ai";
import { getAgentDir } from "../config.ts";
import type { ExtensionAPI, ExtensionFactory } from "../core/extensions/types.ts";
import { getMoahCapabilities, type MoahCapability } from "./capabilities.ts";
import { type MoahRoute, MoahRouter } from "./router.ts";

const PROFILE_FILE = "profile.json";
const PACKAGE_FILE = "package.json";
const WRAPPER_PREFIX = "capability-";
const RELOAD_COMMAND = "moah-apply-profile";

interface ProfileEntry {
	id: string;
	source: string;
	sourceHash: string;
	wrapper: string;
}

interface MoahProfile {
	schema: 1;
	generatedAt: string;
	entries: ProfileEntry[];
}

interface PendingReplay {
	text: string;
	images?: ImageContent[];
}

const pendingReplays = new Map<string, PendingReplay>();

export function moahProfileDir(cwd: string): string {
	return join(cwd, ".moah", "native-active");
}

function assertProfileDir(cwd: string, directory: string): void {
	const expected = resolve(moahProfileDir(cwd));
	const actual = resolve(directory);
	if (actual !== expected || relative(expected, actual) || actual.split(sep).includes("..")) {
		throw new Error("Refusing to modify a profile outside .moah/native-active");
	}
}

function emptyProfile(): MoahProfile {
	return { schema: 1, generatedAt: "", entries: [] };
}

function readProfile(cwd: string, directory = moahProfileDir(cwd)): MoahProfile {
	assertProfileDir(cwd, directory);
	try {
		const parsed: unknown = JSON.parse(readFileSync(join(directory, PROFILE_FILE), "utf8"));
		if (
			typeof parsed !== "object" ||
			parsed === null ||
			(parsed as MoahProfile).schema !== 1 ||
			!Array.isArray((parsed as MoahProfile).entries)
		) {
			throw new Error("Invalid managed MoAH profile");
		}
		return parsed as MoahProfile;
	} catch (error) {
		if (error instanceof Error && "code" in error && error.code === "ENOENT") return emptyProfile();
		throw error;
	}
}

function writeProfile(directory: string, profile: MoahProfile): void {
	const target = join(directory, PROFILE_FILE);
	const temporary = `${target}.${process.pid}.${Date.now()}.tmp`;
	writeFileSync(temporary, `${JSON.stringify(profile, null, 2)}\n`, "utf8");
	renameSync(temporary, target);
}

/** Make the directory a stable Pi extension source before Pi first starts. */
export function ensureMoahProfile(cwd: string): string {
	const directory = moahProfileDir(cwd);
	assertProfileDir(cwd, directory);
	mkdirSync(directory, { recursive: true });
	writeFileSync(
		join(directory, PACKAGE_FILE),
		`${JSON.stringify({ name: "moah-native-active", private: true, type: "module", pi: { extensions: [`${WRAPPER_PREFIX}*.ts`] } }, null, 2)}\n`,
		"utf8",
	);
	if (!existsSync(join(directory, PROFILE_FILE))) writeProfile(directory, emptyProfile());
	return directory;
}

function wrapperName(id: string): string {
	return `${WRAPPER_PREFIX}${id.replace(/[^a-zA-Z0-9_-]/g, "-")}.ts`;
}

function sourceHash(source: string): string {
	return createHash("sha256").update(readFileSync(source)).digest("hex");
}

export function stageMoahProfile(cwd: string, selectedIds: string[]): MoahProfile {
	const directory = ensureMoahProfile(cwd);
	const byId = new Map(getMoahCapabilities().map((capability) => [capability.id, capability]));
	const uniqueIds = [...new Set(selectedIds)].sort();
	const missing = uniqueIds.filter((id) => !byId.has(id));
	if (missing.length > 0) throw new Error(`Unknown MoAH capability: ${missing.join(", ")}`);
	const entries: ProfileEntry[] = uniqueIds.map((id) => {
		const capability = byId.get(id) as MoahCapability;
		return { id, source: capability.entry, sourceHash: sourceHash(capability.entry), wrapper: wrapperName(id) };
	});
	const previous = readProfile(cwd, directory);
	for (const entry of entries) {
		const sourceUrl = pathToFileURL(entry.source).href;
		writeFileSync(
			join(directory, entry.wrapper),
			`// Generated by MoAH; the implementation remains in the shipped Pi example.\n// source-sha256=${entry.sourceHash}\nexport { default } from ${JSON.stringify(sourceUrl)};\n`,
			"utf8",
		);
	}
	const next = new Set(entries.map((entry) => entry.wrapper));
	for (const entry of previous.entries) {
		if (!next.has(entry.wrapper) && entry.wrapper.startsWith(WRAPPER_PREFIX) && entry.wrapper.endsWith(".ts")) {
			rmSync(join(directory, entry.wrapper), { force: true });
		}
	}
	const profile: MoahProfile = { schema: 1, generatedAt: new Date().toISOString(), entries };
	writeProfile(directory, profile);
	return profile;
}

function sameIds(left: Iterable<string>, right: Iterable<string>): boolean {
	const first = new Set(left);
	const second = new Set(right);
	return first.size === second.size && [...first].every((id) => second.has(id));
}

function profileStatus(cwd: string): Record<string, unknown> {
	const directory = ensureMoahProfile(cwd);
	const profile = readProfile(cwd, directory);
	return {
		directory,
		generatedAt: profile.generatedAt || null,
		capabilities: profile.entries.map((entry) => ({
			id: entry.id,
			source: entry.source,
			sourceHash: entry.sourceHash,
			sourceHashMatches: existsSync(entry.source) && sourceHash(entry.source) === entry.sourceHash,
			wrapperPresent: existsSync(join(directory, entry.wrapper)),
		})),
	};
}

export function createMoahExtension(options: { cwd?: string } = {}): ExtensionFactory {
	return async (pi: ExtensionAPI) => {
		const cwd = options.cwd ?? process.cwd();
		const profileDirectory = ensureMoahProfile(cwd);
		const cacheDirectory = join(getAgentDir(), "moah", "router");
		const router = new MoahRouter(cacheDirectory);
		let activeProfile = new Set(readProfile(cwd, profileDirectory).entries.map((entry) => entry.id));
		let lastRoute: Pick<MoahRoute, "selected" | "ranked"> | undefined;

		pi.registerCommand(RELOAD_COMMAND, {
			description: "Internal: reload MoAH's generated capability profile",
			handler: async (_args, ctx) => {
				await ctx.reload();
			},
		});

		pi.on("input", async (event, ctx) => {
			if (event.source === "extension" || event.text.startsWith("/")) return { action: "continue" };
			try {
				const route = await router.route(event.text, getMoahCapabilities());
				lastRoute = { selected: route.selected, ranked: route.ranked };
				if (sameIds(route.selected, activeProfile)) return { action: "continue" };
				const profile = stageMoahProfile(cwd, route.selected);
				activeProfile = new Set(profile.entries.map((entry) => entry.id));
				pendingReplays.set(profileDirectory, { text: event.text, images: event.images });
				ctx.ui.notify(
					`MoAH: profilo semantico ${route.selected.length ? route.selected.join(", ") : "Pi core"}; ricarico senza riscaricare l'agente.`,
					"info",
				);
				pi.sendUserMessage(`/${RELOAD_COMMAND}`, { deliverAs: "followUp", expandPromptTemplates: true });
				return { action: "handled" };
			} catch (error) {
				const message = error instanceof Error ? error.message : String(error);
				ctx.ui.notify(
					`MoAH: router locale non pronto (${message}). Esegui /moah setup; continuo con Pi core.`,
					"warning",
				);
				return { action: "continue" };
			}
		});

		pi.on("session_start", async (_event, ctx) => {
			const profile = readProfile(cwd, profileDirectory);
			activeProfile = new Set(profile.entries.map((entry) => entry.id));
			const profileSources = new Set(profile.entries.map((entry) => resolve(profileDirectory, entry.wrapper)));
			const addedTools = pi
				.getAllTools()
				.filter((tool) => profileSources.has(resolve(tool.sourceInfo.path)))
				.map((tool) => tool.name);
			if (addedTools.length > 0) pi.setActiveTools([...new Set([...pi.getActiveTools(), ...addedTools])]);
			const replay = pendingReplays.get(profileDirectory);
			if (replay) {
				pendingReplays.delete(profileDirectory);
				const content = replay.images?.length
					? [{ type: "text" as const, text: replay.text }, ...replay.images]
					: replay.text;
				pi.sendUserMessage(content);
			}
			ctx.ui.setStatus("moah", `MoAH router · ${activeProfile.size} capability`);
		});

		pi.registerCommand("moah", {
			description: "MoAH router status, local-model setup, or active capability profile",
			handler: async (args, ctx) => {
				const command = args.trim();
				if (command === "setup") {
					ctx.ui.notify("MoAH: scarico/preparo il modello semantico locale…", "info");
					await mkdir(cacheDirectory, { recursive: true });
					await router.setup();
					ctx.ui.notify(
						"MoAH: router locale pronto. I prompt successivi selezioneranno il profilo nativo.",
						"info",
					);
					return;
				}
				const profile = profileStatus(cwd);
				ctx.ui.notify(
					JSON.stringify(
						{ router: { model: "Xenova/multilingual-e5-small", cacheDirectory }, profile, lastRoute },
						null,
						2,
					),
					"info",
				);
			},
		});
	};
}
